services:
    grafana:
        environment:
            - ANALYTICS_DB_HOST=${ANALYTICS_DB_HOST:-missing_ANALYTICS_DB_HOST}
            - ANALYTICS_DB_PASSWORD=${ANALYTICS_DB_PASSWORD:-missing_ANALYTICS_DB_PASSWORD}
            - ANALYTICS_DB_PORT=${ANALYTICS_DB_PORT:-missing_ANALYTICS_DB_PORT}
            - ANALYTICS_DB_USER=${ANALYTICS_DB_USER:-missing_ANALYTICS_DB_USER}
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
            - HOST_DOMAIN=${HOST_DOMAIN}
            - HOST_PORT=80
