function [structOut] = identify(structIn)
warning off;

technique = structIn.technique;
params = structIn.params;
fs = structIn.fs;

if (structIn.transposing)
   data = structIn.data.';
else
   data = structIn.data;
end

if strcmp(technique, 'ssi')
    [fd,shapes,zt,rf,stdfd,stdzt] = ssiId( ...
        data, ...
        fs, ...
        params.npoints, ...
        params.order, ...
        params.freqtol, ...
        params.mactol, ...
        params.minfound ...
        );
elseif strcmp(technique, 'next-era')
    t = 0 : 1/fs :(size(data,1)-1)/frs;
    [fd,shapes,zt,rf,stdfd,stdzt] = neraId( ...
        data, ...
        t, ...
        params.refch, ...
        params.npoints, ...
        params.order, ...
        params.freqtol, ...
        params.mactol, ...
        params.minfound ...
        );
else
    error('Unsupported modal identification technique')
end

structOut = struct( ...
    'fd', fd, ...
    'shapes', shapes, ...
    'zt', zt, ...
    'rf', rf, ...
    'stdfd', stdfd.', ...
    'stdzt', stdzt.'  ...
    );
