version: "3.9"
services:
  live:
    build:
      context: ${PATH_SERVICE_LIVE:-.}
      args:
        - NODE_ENV=development
    command: "npm run dev"
    environment:
      - NODE_ENV=development
    volumes:
      - ${PATH_SERVICE_LIVE:-.}/src:/app/src/
