FROM node:14 AS builder
ARG REACT_APP_IDENTITY_AUTH_DOMAIN
ARG REACT_APP_IDENTITY_API_KEY

ENV REACT_APP_IDENTITY_AUTH_DOMAIN=$REACT_APP_IDENTITY_AUTH_DOMAIN
ENV REACT_APP_IDENTITY_API_KEY=$REACT_APP_IDENTITY_API_KEY
ENV NODE_ENV=production

WORKDIR /app
COPY package*.json ./
RUN npm i --silent
COPY ./ ./
RUN npm run build


FROM nginx:1.21
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY nginx.default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build .
