version: "3.9"
services:
  registry:
    build:
      context: ${PATH_SERVICE_REGISTRY:-.}
      args:
        - NODE_ENV=production
    environment:
      - MEASURES_FILES_BUCKET=${GS_BUCKET_MEASURES_BATCH}
      - MEASURES_FILES_STORAGE_MODE=${MEASURES_FILES_STORAGE_MODE:-gs}
      - NODE_ENV=production
