{
 "title": "Modal - execution",
 "tags": [
  "execution",
  "modal"
 ],
 "time": { "from": "2019-09-10T22:17:07.000Z", "to": "2019-09-10T22:36:59.000Z" },
 "templating": {
  "list": [
   { "name": "execution_id" }
  ]
 },
 "panels": [
  {
   "title": "Response metrics",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    time,\r\n    channel_id AS \"Channel\",\r\n    max_abs AS \"Max amplitude [g]\",\r\n    std AS \"STD\"\r\nFROM (\r\n        SELECT jsonb_object_keys(data) AS channel_id\r\n        FROM results\r\n        WHERE metadata->>'execution_id' = '$execution_id'\r\n          AND metadata->>'type'='response_metrics'\r\n    ) channels\r\n    JOIN LATERAL (\r\n        SELECT\r\n            (metadata->>'time_start')::TIMESTAMPTZ AS time,\r\n            data->channel_id->'max' AS max_abs,\r\n            data->channel_id->'std' AS std\r\n        FROM results\r\n        WHERE metadata->>'execution_id' = '$execution_id'\r\n          AND metadata->>'type'='response_metrics'\r\n    ) join_lat ON true\r\nWHERE $__timeFilter(\"time\")\r\nGROUP BY 1, 2, 3, 4\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Response",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "accG" } },
   "targets": [
    {
     "rawSql": "SELECT time,\r\n    channel_id AS metric,\r\n    channel_data AS value\r\nFROM (\r\n        SELECT jsonb_object_keys(data) AS channel_id\r\n        FROM measures\r\n    ) channels\r\n    JOIN LATERAL (\r\n        SELECT generate_series(\r\n                (metadata->>'time_start')::TIMESTAMPTZ,\r\n                (metadata->>'time_end')::TIMESTAMPTZ,\r\n                make_interval(\r\n                    secs => (1 / (metadata->>'sampling_rate')::NUMERIC)\r\n                )\r\n            ) AS time,\r\n            jsonb_array_elements(data->channel_id)::NUMERIC AS channel_data\r\n        FROM measures\r\n        WHERE metadata->>'execution_id' = '$execution_id'\r\n    ) join_lat ON true\r\nWHERE $__timeFilter(\"time\")\r\nGROUP BY 1, 2, 3\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Modal identification",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time,\r\n  jsonb_array_elements(data->'rf')::DOUBLE PRECISION AS \"Repetitions\",\r\n  jsonb_array_elements(data->'fd')::DOUBLE PRECISION AS \"Frequency [Hz]\",\r\n  jsonb_array_elements(data->'zt')::DOUBLE PRECISION AS \"Damping [%]\"\r\nFROM (\r\n        SELECT data, (metadata->>'time_start')::TIMESTAMPTZ AS time\r\n        FROM results\r\n        WHERE metadata->>'execution_id' = '$execution_id'\r\n          AND (metadata->>'time_start')::TIMESTAMPTZ BETWEEN $__timeFrom() AND $__timeTo()\r\n    ) d(data)\r\nORDER BY \"Repetitions\" DESC;"
    }
   ]
  },
  {
   "title": "Modal identification",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT (metadata->>'time_start')::TIMESTAMPTZ AS time,\r\n  jsonb_array_elements(data->'fd')::DOUBLE PRECISION AS \"Frequency [Hz]\",\r\n  jsonb_array_elements(data->'zt')::DOUBLE PRECISION AS \"Damping [%]\"\r\nFROM results\r\nWHERE metadata->>'execution_id' = '$execution_id'\r\n  AND (metadata->>'time_start')::TIMESTAMPTZ BETWEEN $__timeFrom() AND $__timeTo()\r\nORDER BY 1;"
    }
   ]
  }
 ]
}