services:
  users:
    command: "npm run debug"
    environment:
      - DEBUG_PORT=9229
    ports:
      - ${PORT_HOST_SERVICE_USERS:-3000}:${PORT_SERVICE_USERS:-3000}
      - ${PORT_HOST_DEBUG_SERVICE_USERS:-9229}:9229
    volumes:
      - ${PATH_SERVICE_USERS:-.}/src:/app/src/
